// <auto-generated />
using System;
using JourneyJournal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JourneyJournal.Data.Migrations
{
    [DbContext(typeof(JourneyJournalDbContext))]
    [Migration("20260118165552_MakeTripPointDatesRequired")]
    partial class MakeTripPointDatesRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("JourneyJournal.Data.Entities.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccommodationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripPointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("AccommodationId");

                    b.HasIndex("TripPointId");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("TripId", "Category");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.PlaceToVisit", b =>
                {
                    b.Property<int>("PlaceToVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterVisitNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<short>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<short?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TripPointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsefulLinks")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("PlaceToVisitId");

                    b.HasIndex("TripPointId");

                    b.HasIndex("VisitDate");

                    b.HasIndex("TripPointId", "Order");

                    b.ToTable("PlacesToVisit");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromPointId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransportationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RouteId");

                    b.HasIndex("IsSelected");

                    b.HasIndex("ToPointId");

                    b.HasIndex("FromPointId", "ToPointId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TripId");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("StartDate");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.TripPoint", b =>
                {
                    b.Property<int>("TripPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TripPointId");

                    b.HasIndex("TripId", "Order");

                    b.ToTable("TripPoints");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Accommodation", b =>
                {
                    b.HasOne("JourneyJournal.Data.Entities.TripPoint", "TripPoint")
                        .WithMany("Accommodations")
                        .HasForeignKey("TripPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripPoint");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Expense", b =>
                {
                    b.HasOne("JourneyJournal.Data.Entities.Trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.PlaceToVisit", b =>
                {
                    b.HasOne("JourneyJournal.Data.Entities.TripPoint", "TripPoint")
                        .WithMany("PlacesToVisit")
                        .HasForeignKey("TripPointId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TripPoint");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Route", b =>
                {
                    b.HasOne("JourneyJournal.Data.Entities.TripPoint", "FromPoint")
                        .WithMany("RoutesFrom")
                        .HasForeignKey("FromPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JourneyJournal.Data.Entities.TripPoint", "ToPoint")
                        .WithMany("RoutesTo")
                        .HasForeignKey("ToPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromPoint");

                    b.Navigation("ToPoint");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.TripPoint", b =>
                {
                    b.HasOne("JourneyJournal.Data.Entities.Trip", "Trip")
                        .WithMany("TripPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.Trip", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("TripPoints");
                });

            modelBuilder.Entity("JourneyJournal.Data.Entities.TripPoint", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("PlacesToVisit");

                    b.Navigation("RoutesFrom");

                    b.Navigation("RoutesTo");
                });
#pragma warning restore 612, 618
        }
    }
}
